### ISSUE TITLE
Error loading Cuboids2 after creating a zone (apparently welcome message related)

### ISSUE THREAD

**Issue by BluXDragon** [damagefilter/Cuboids#11]
Steps to reproduce:
-Install Cuboids2
-Create a zone. In my instance, "/highprotect o:BluXDragon test"
-Perform save command (/cmod save)
-Disable and enable (reload) Cuboids2.
-Cuboids2 will not load, throwing the below error.

```
2013-05-08 02:22:56 [INFO] [Cuboids2] Loading Cuboids2 ...

2013-05-08 02:22:56 [INFO] [Cuboids2] Version ... 4.0.0

2013-05-08 02:22:56 [INFO] [Cuboids2] Looking for CuboidPlugin files...
Nothing foreign to load found
2013-05-08 02:22:56 [WARNING] [CanaryMod] Could not enable Cuboids2
java.lang.NullPointerException
        at net.playblack.cuboids.regions.Region.setWelcome(Region.java:1044)
        at net.playblack.cuboids.datasource.XmlData.domToRegion(XmlData.java:240)
        at net.playblack.cuboids.datasource.XmlData.loadAll(XmlData.java:89)
        at net.playblack.cuboids.regions.RegionManager.load(RegionManager.java:61)
        at net.playblack.cuboids.Bootstrapper.<init>(Bootstrapper.java:115)
        at net.playblack.cuboids.impl.canarymod.Cuboids2.enable(Cuboids2.java:21)
        at net.canarymod.plugin.PluginLoader.enablePlugin(PluginLoader.java:558)
        at net.canarymod.plugin.PluginLoader.enablePlugin(PluginLoader.java:534)
        at net.canarymod.plugin.PluginLoader.reloadPlugin(PluginLoader.java:668)
        at net.canarymod.commandsys.commands.PluginCommand.reload(PluginCommand.java:42)
        at net.canarymod.commandsys.commands.PluginCommand.execute(PluginCommand.java:29)
        at net.canarymod.commandsys.CommandList.reloadPluginCommand(CommandList.java:548)
        at sun.reflect.GeneratedMethodAccessor60.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at net.canarymod.commandsys.CommandManager$1.execute(CommandManager.java:253)
        at net.canarymod.commandsys.CanaryCommand.parseCommand(CanaryCommand.java:63)
        at net.canarymod.commandsys.CommandManager.parseCommand(CommandManager.java:132)
        at net.canarymod.api.entity.living.humanoid.CanaryPlayer.executeCommand(CanaryPlayer.java:297)
        at net.canarymod.api.entity.living.humanoid.CanaryPlayer.chat(CanaryPlayer.java:105)
        at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:618)
        at net.minecraft.server.Packet3Chat.a(Packet3Chat.java:40)
        at net.minecraft.server.TcpConnection.b(TcpConnection.java:284)
        at net.minecraft.server.NetServerHandler.d(NetServerHandler.java:72)
        at net.minecraft.server.NetworkListenThread.b(NetworkListenThread.java:32)
        at net.minecraft.server.DedicatedServerListenThread.b(DedicatedServerListenThread.java:24)
        at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:477)
        at net.minecraft.server.DedicatedServer.r(DedicatedServer.java:197)
        at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:392)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:331)
        at net.minecraft.server.ThreadMinecraftServer.run(ThreadMinecraftServer.java:13)
```

The file of the region created;

```
<region>
  <meta>
    <welcome></welcome>
    <farewell></farewell>
    <name>test</name>
    <priority>0</priority>
    <world>default</world>
    <dimension>0</dimension>
    <origin>[2583.0,255.0,2086.0]</origin>
    <offset>[2581.0,0.0,2084.0]</offset>
    <players>o:BluXDragon</players>
    <groups>no_groups</groups>
  </meta>
  <properties>
    <protection>ALLOW</protection>
    <lava-bucket>DENY</lava-bucket>
    <water-bucket>DEFAULT</water-bucket>
    <creative>DENY</creative>
    <physics>ALLOW</physics>
    <mob-spawn>ALLOW</mob-spawn>
    <water-flow>ALLOW</water-flow>
    <tnt-explosion>ALLOW</tnt-explosion>
    <enderman-pickup>DENY</enderman-pickup>
    <creeper-explosion>DENY</creeper-explosion>
    <enter-cuboid>ALLOW</enter-cuboid>
    <restrict-items>DEFAULT</restrict-items>
    <lava-flow>ALLOW</lava-flow>
    <firespread>ALLOW</firespread>
    <animal-spawn>ALLOW</animal-spawn>
    <mob-damage>ALLOW</mob-damage>
    <pvp-damage>ALLOW</pvp-damage>
    <more-mobs>DENY</more-mobs>
    <healing>DENY</healing>
    <crops-trampling>DENY</crops-trampling>
  </properties>
</region>
```

**Comment by damagefilter** [comment]
at net.playblack.cuboids.regions.Region.setWelcome(Region.java:1044)
That line is setting the offset vector in my sources ... apparently I forgot to make one or two releases here xD
This should be fixed.
